config/routes.rb
Rails.application.routes.draw do
  get 'up' => 'rails/health#show', as: :rails_health_check

  # add the glob route (captures filenames with dots)
  get "/files/*filename/download", to: "files#download", as: :download_file

  # keep the resources for index/create
  resources :files, only: [:index, :create], param: :filename

  root to: "files#index"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/files_controller.rb
class FilesController < ApplicationController
  STORAGE_DIR = Rails.root.join('storage', 'uploads')

  before_action :ensure_storage_dir!

  def index
    @files = Dir.children(STORAGE_DIR).sort.map do |name|
      path = STORAGE_DIR.join(name)
      {
        name: name,
        size: path.size,
        mtime: path.mtime
      }
    end
  end

  def download
    filename = params[:filename].to_s
    safe_name = File.basename(filename) # avoid path traversal
    file = STORAGE_DIR.join(safe_name)
    head :not_found and return unless file.file?

    # send_file with streaming enabled for large files
    send_file file,
              disposition: 'attachment',
              filename: safe_name,
              stream: true,
              buffer_size: 64.kilobytes
  end

  def create
    uploaded = params[:file]
    redirect_to files_path, alert: 'No file selected' and return unless uploaded.respond_to?(:original_filename)

    safe_name = File.basename(uploaded.original_filename)
    dest = STORAGE_DIR.join(safe_name)

    # Write efficiently from temp file to destination (doesn't load into memory)
    File.open(dest, 'wb') do |f|
      IO.copy_stream(uploaded.tempfile, f)
    end

    redirect_to files_path, notice: "Uploaded #{safe_name}"
  end

  private

  def ensure_storage_dir!
    FileUtils.mkdir_p(STORAGE_DIR) unless STORAGE_DIR.exist?
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/files/index.html.erb
<h1>Files</h1>

<% if notice %>
  <p style="color:green"><%= notice %></p>
<% end %>
<% if alert %>
  <p style="color:red"><%= alert %></p>
<% end %>

<table style="width:100%;border-collapse:collapse">
  <thead>
    <tr>
      <th style="text-align:left">Name</th>
      <th style="text-align:right">Size</th>
      <th style="text-align:right">Download</th>
    </tr>
  </thead>
  <tbody>
    <% @files.each do |f| %>
      <tr style="border-top:1px solid #eee">
        <td><%= f[:name] %></td>
        <td style="text-align:right"><%= number_to_human_size(f[:size]) %></td>
        <td style="text-align:right">
          <%= link_to "Download", download_file_path(filename: f[:name]), class: "btn", rel: "noopener" %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<hr>

<h2>Upload</h2>
<%= form_with url: files_path, multipart: true, local: true do |form| %>
  <%= file_field_tag :file %>
  <%= submit_tag "Upload" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DataBridge</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header style="padding:8px;border-bottom:1px solid #eee">
      <nav>
        <%= link_to "Home", root_path %> |
        <%= link_to "Files", files_path %>
      </nav>
    </header>

    <main style="padding:16px">
      <%= yield %>
    </main>
  </body>
</html>